//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardMatab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matab_PMH
    {
        public long ID { get; set; }
        public long ParvandeCode { get; set; }
        public int UserID { get; set; }
        public string ModifyDate { get; set; }
        public string PMH { get; set; }
        public string Allergies { get; set; }
        public string RoutineMedications { get; set; }
        public string SocialHistory { get; set; }
    }
}
