//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardMatab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matab_Visit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Matab_Visit()
        {
            this.Matab_VisitDrug = new HashSet<Matab_VisitDrug>();
        }
    
        public long ID { get; set; }
        public string VisitDate { get; set; }
        public Nullable<long> ParvandeCode { get; set; }
        public string PatientsComplaints { get; set; }
        public string PresentIllness { get; set; }
        public string VisitPlan { get; set; }
        public string Diagnose { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Hight { get; set; }
        public Nullable<double> Head { get; set; }
        public Nullable<double> Systolic { get; set; }
        public Nullable<double> Diastolic { get; set; }
        public Nullable<double> DrugDose { get; set; }
        public Nullable<int> DocID { get; set; }
        public string DrugDesc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matab_VisitDrug> Matab_VisitDrug { get; set; }
    }
}
