//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardMatab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matab_LabTests
    {
        public long ID { get; set; }
        public Nullable<long> ParvandeCode { get; set; }
        public Nullable<int> TestCode { get; set; }
        public string LabDate { get; set; }
        public string LabResult { get; set; }
        public Nullable<decimal> MinRange { get; set; }
        public Nullable<decimal> MaxRange { get; set; }
        public string RangeComment { get; set; }
        public string LabResultDate { get; set; }
    }
}
