//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardMatab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matab_VisitDrug
    {
        public long ID { get; set; }
        public long Matab_VisitID { get; set; }
        public int DrugID { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<double> DrugOrderID { get; set; }
        public string DrugDose { get; set; }
    
        public virtual Matab_Visit Matab_Visit { get; set; }
    }
}
