//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardMatab.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MatabDBEntities : DbContext
    {
        public MatabDBEntities()
            : base("name=MatabDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblParvande> TblParvande { get; set; }
        public virtual DbSet<Matab_PMH> Matab_PMH { get; set; }
        public virtual DbSet<Matab_Visit> Matab_Visit { get; set; }
        public virtual DbSet<Matab_LabTests> Matab_LabTests { get; set; }
        public virtual DbSet<TblLabTests> TblLabTests { get; set; }
        public virtual DbSet<Matab_VisitDrug> Matab_VisitDrug { get; set; }
        public virtual DbSet<tbl_DrugOrder> tbl_DrugOrder { get; set; }
        public virtual DbSet<TblDrugs> TblDrugs { get; set; }
    }
}
