//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardMatab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDrugs
    {
        public int DrgID { get; set; }
        public string BrandName { get; set; }
        public string GenericName { get; set; }
        public string Strength { get; set; }
        public string Direction { get; set; }
        public string Quantity { get; set; }
        public string Refills { get; set; }
        public bool DEAneed { get; set; }
        public bool DEAnotNeed { get; set; }
        public Nullable<int> DrgOrderID { get; set; }
        public Nullable<double> DrgCount { get; set; }
        public Nullable<int> DrgSectionID { get; set; }
        public Nullable<bool> Invisible { get; set; }
        public Nullable<double> DrgMojoodi { get; set; }
    }
}
