//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardMatab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLabTests
    {
        public Nullable<short> TestType { get; set; }
        public int TestCode { get; set; }
        public string TestName { get; set; }
        public Nullable<decimal> LowVal { get; set; }
        public Nullable<decimal> HighVal { get; set; }
        public string UnitMeasure { get; set; }
        public bool Pos { get; set; }
        public bool Neg { get; set; }
        public Nullable<decimal> NormalVal { get; set; }
        public string TestFullName { get; set; }
        public string TestNationalCode { get; set; }
    }
}
