//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardMatab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblParvande
    {
        public long ParvandeID { get; set; }
        public Nullable<long> ParvandeCode { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public Nullable<int> InsID { get; set; }
        public string InsBookNo { get; set; }
        public string DateEtebar { get; set; }
        public Nullable<int> InsAddID { get; set; }
        public string InsAddBookNo { get; set; }
        public Nullable<int> OzvID { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string DateTashkil { get; set; }
        public Nullable<int> UserID { get; set; }
        public string SaatSabt { get; set; }
        public string Email { get; set; }
        public string BurnDate { get; set; }
        public string MelliCode { get; set; }
        public Nullable<int> Doctor_Default { get; set; }
        public string ParvandeNumDasti { get; set; }
        public Nullable<int> SectionID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsAlarmInPaziresh { get; set; }
        public Nullable<int> National_Id { get; set; }
        public string parent { get; set; }
        public Nullable<int> Taahol { get; set; }
        public string Shoghl { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> SkineType { get; set; }
        public Nullable<int> State { get; set; }
        public string City { get; set; }
        public string Fax { get; set; }
        public string JobFax { get; set; }
        public string ShomareShenasname { get; set; }
        public Nullable<int> MoarefID { get; set; }
        public string VIPCardID { get; set; }
        public Nullable<bool> IsConnectToMehrYasanCRM { get; set; }
        public Nullable<int> Ashnayi { get; set; }
        public string Location { get; set; }
        public Nullable<int> Degree { get; set; }
        public int Age { get; set; }
    }
}
